# Configurações do Servidor e Aplicação
server:
  port: ${PORT:0}

spring:
  application:
    name: ms-notification

  # Configurações do MongoDB (Banco de Dados NoSQL)
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:notification-db}
      username: ${MONGO_USERNAME:user_admin_mongodb}
      password: ${MONGO_PASSWORD:password_admin_mongodb}
      authentication-database: admin

  # Configurações de Mensageria (RabbitMQ)
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  # Configurações de e-mail
  mail:
    host: ${HOST_MAIL}
    port: ${PORT}
    username: ${HOST_USERNAME}
    password: ${HOST_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  output:
    ansi:
      enabled: ALWAYS

# Configurações de Log
logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: info
    br:
      com:
        bgrbarbosa:
          ms-notification: info

#Configuração do Eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: ms-registry
    non-secure-port: ${server.port}
  client:
    service-url:
      defaultZone: ${URL_SERVICE_DISCOVERY:http://localhost:8761/eureka}