server:
  port: ${PORT:0}
spring:
  application:
    name: MS-SCHEDULING
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/scheduling-db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:example}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public

  output:
    ansi:
      enabled: ALWAYS

#Configurações do RabbitMQ
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

# Configuracoes de log
logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: info
    br:
      com:
        bgrbarbosa:
          ms-exame: info

# Coonfigurações da AWS
cloud:
  aws:
    credentials:
      access-key: ${AWS_KEY_ACCESS}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
aws:
  bucket:
    name: ${AWS_BUCKET}

#Configuração do Eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: ms-registry
    non-secure-port: ${server.port}
  client:
    service-url:
      defaultZone: ${URL_SERVICE_DISCOVERY:http://localhost:8761/eureka}


